### PR TITLE
Make directive template urls dynamic by passing it through attributes

### PR DESCRIPTION
**Pull request by yvesvanbroekhoven**
Hi,

I was thinking it would be nice to have a dynamic template URL for the directives, as every project is different. I'm not sure if this is the right way to approach this problem. Let me know what you think.

### CODE REVIEW

**Comment by snapjay** [comment]
I really like the look of this and it's a feature that's been asked for.
Not sure what the AngularJS official stance of this is, but this way it looks great.
I look into it more.

**Comment by vlapo** [comment]
+1 ... We use custom stack with custom directory structure

**Comment by amejiarosario** [comment]
+1, nice I was looking for that

**Comment by snapjay** [comment]
Thanks guys; this looks great!

**Pull request merged**
